### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by Novinnam** [Iranopensourceai/hybrid_deeplearning_on_brain_tumor#2]
Tasks:
- Resize, Normalize, ...
- Data collection

**Comment by vahid-karami** [comment]
Hello there,
Are you ok for a coordination meeting tonight at 8 pm?! 
@F-Shahbazi 
@sadafsattarzadeh

**Comment by F-Shahbazi** [comment]
Hi Vahid. that's ok with me.

**Comment by F-Shahbazi** [comment]
> Hello there, Are you ok for a coordination meeting tonight at 8 pm?! @F-Shahbazi @sadafsattarzadeh

Hi Vahid. that's ok with me.
